// kb.js — 40 Q&A per category (iPhone, Tablet, Google, Phone, Drone, Desktop, Laptop, Watch, Gaming, Microwave)

const KB = [
  /* iPHONE (40) — prefix IPH_ */
  {id:'IPH_01', cat:'iPhone', q:'iPhone not charging', a:'Try different cable/charger, clean Lightning port, force restart; replace port or battery if hardware.', tags:['charging']},
  {id:'IPH_02', cat:'iPhone', q:'Battery drains fast', a:'Check battery health in settings, reduce background app refresh and brightness; replace battery if <80%.', tags:['battery']},
  {id:'IPH_03', cat:'iPhone', q:'iPhone overheats', a:'Close heavy apps, remove case, avoid charging in sun; update iOS and apps.', tags:['overheat']},
  {id:'IPH_04', cat:'iPhone', q:'Face ID not working', a:'Ensure nothing blocks TrueDepth camera, update iOS, reset Face ID and re-enroll face.', tags:['faceid','camera']},
  {id:'IPH_05', cat:'iPhone', q:'iPhone frozen/black screen', a:'Force restart (volume up, volume down, hold side), connect to charger and try again.', tags:['boot']},
  {id:'IPH_06', cat:'iPhone', q:'Apps crashing', a:'Update apps/iOS, offload or reinstall offending app, free storage.', tags:['apps']},
  {id:'IPH_07', cat:'iPhone', q:'No sound from speaker', a:'Check volume & mute switch, disable Bluetooth, clean speaker grill, restart.', tags:['audio']},
  {id:'IPH_08', cat:'iPhone', q:'Wi-Fi disconnects', a:'Forget network, reboot router & phone, reset network settings.', tags:['wifi']},
  {id:'IPH_09', cat:'iPhone', q:'Slow performance', a:'Check storage and battery health; update iOS; disable background refresh.', tags:['speed']},
  {id:'IPH_10', cat:'iPhone', q:'Touchscreen unresponsive', a:'Remove screen protector, clean display, force restart; replace digitizer if hardware.', tags:['touch']},
  {id:'IPH_11', cat:'iPhone', q:'Camera blurry', a:'Clean lens, close and reopen Camera app, test other camera apps, repair if physical.', tags:['camera']},
  {id:'IPH_12', cat:'iPhone', q:'Unable to update iOS', a:'Free up storage, plug into power & Wi-Fi, try updating via Finder/iTunes.', tags:['update']},
  {id:'IPH_13', cat:'iPhone', q:'SIM not detected', a:'Reseat SIM, test SIM in another phone, reset network settings.', tags:['sim','network']},
  {id:'IPH_14', cat:'iPhone', q:'Bluetooth pairing fails', a:'Toggle Bluetooth, remove old pairings, restart both devices.', tags:['bluetooth']},
  {id:'IPH_15', cat:'iPhone', q:'iMessage not sending', a:'Check network, sign out/in of Apple ID, enable iMessage under settings.', tags:['imessage']},
  {id:'IPH_16', cat:'iPhone', q:'FaceTime poor quality', a:'Use Wi-Fi, close other apps, update iOS, test on another connection.', tags:['facetime']},
  {id:'IPH_17', cat:'iPhone', q:'Green tint on display', a:'Update iOS, reboot; if persists possible hardware issue (screen), visit repair.', tags:['display']},
  {id:'IPH_18', cat:'iPhone', q:'Charging slow', a:'Try higher watt charger, clean port, test wireless charging pad.', tags:['charging']},
  {id:'IPH_19', cat:'iPhone', q:'Apps notifications not appearing', a:'Check app notification settings and Focus/Do Not Disturb.', tags:['notifications']},
  {id:'IPH_20', cat:'iPhone', q:'Water exposure — what to do', a:'Power off immediately, dry and leave open in airflow; do not charge until dry; seek repair if symptoms persist.', tags:['water']},

  {id:'IPH_21', cat:'iPhone', q:'Can’t send MMS', a:'Ensure MMS is enabled, check cellular data and APN settings, restart device.', tags:['mms','network']},
  {id:'IPH_22', cat:'iPhone', q:'Spotlight search not working', a:'Restart phone, disable/re-enable Siri & Search for affected apps, rebuild index by toggling settings.', tags:['search']},
  {id:'IPH_23', cat:'iPhone', q:'Keyboard lag or autocorrect issues', a:'Reset keyboard dictionary, update iOS, remove third-party keyboards to test.', tags:['keyboard']},
  {id:'IPH_24', cat:'iPhone', q:'Unable to restore from backup', a:'Check iCloud/PC backup integrity, stable Wi-Fi, sufficient storage on device.', tags:['backup','restore']},
  {id:'IPH_25', cat:'iPhone', q:'Location services not accurate', a:'Enable Location Services, toggle system services, calibrate compass, restart.', tags:['gps','location']},
  {id:'IPH_26', cat:'iPhone', q:'Photos not syncing to iCloud', a:'Check iCloud Photos setting, enough iCloud storage, stable Wi-Fi, sign out/in.', tags:['photos','icloud']},
  {id:'IPH_27', cat:'iPhone', q:'Low call volume for caller', a:'Disable Noise Cancellation, test without case, ensure earpiece unobstructed.', tags:['audio','calls']},
  {id:'IPH_28', cat:'iPhone', q:'Cannot use hotspot', a:'Ensure Personal Hotspot enabled, mobile data on, carrier supports hotspot and correct APN.', tags:['hotspot','network']},
  {id:'IPH_29', cat:'iPhone', q:'SOS or Emergency only', a:'Check SIM/plan, toggle airplane mode, reseat SIM, contact carrier.', tags:['network','sim']},
  {id:'IPH_30', cat:'iPhone', q:'Widgets not updating', a:'Remove and re-add widget, open host app, check background refresh.', tags:['widgets']},
  {id:'IPH_31', cat:'iPhone', q:'Screen rotation stuck', a:'Toggle portrait lock, restart device, check specific app rotation settings.', tags:['display']},
  {id:'IPH_32', cat:'iPhone', q:'Storage “Other” huge', a:'Clear Safari cache, offload unused apps, backup & restore to reclaim space.', tags:['storage']},
  {id:'IPH_33', cat:'iPhone', q:'Siri not responding', a:'Check Siri & Dictation settings, microphone access, and language; restart.', tags:['siri']},
  {id:'IPH_34', cat:'iPhone', q:'AirDrop not visible', a:'Set AirDrop to Everyone/Contacts, toggle Wi-Fi & Bluetooth, restart both devices.', tags:['airdrop']},
  {id:'IPH_35', cat:'iPhone', q:'Face ID failing after repair', a:'TrueDepth hardware may be disconnected or replaced incorrectly — seek authorized service.', tags:['faceid','repair']},
  {id:'IPH_36', cat:'iPhone', q:'Battery percentage not showing', a:'Enable battery percentage in Control Center or Settings, restart if glitchy.', tags:['battery']},
  {id:'IPH_37', cat:'iPhone', q:'Mail not fetching new messages', a:'Check fetch settings, account credentials, remove and re-add mail account.', tags:['mail']},
  {id:'IPH_38', cat:'iPhone', q:'Stuck on Apple logo', a:'Try force restart, connect to Finder/iTunes for recovery, avoid constant restores.', tags:['boot','recovery']},
  {id:'IPH_39', cat:'iPhone', q:'Cannot install app due to “Waiting”', a:'Pause and resume download, sign out/in of App Store, restart device.', tags:['apps','appstore']},
  {id:'IPH_40', cat:'iPhone', q:'Cellular data not switching to 4G/5G', a:'Check network mode settings, carrier provisioning, restart device and toggle cellular.', tags:['network','4g','5g']},

  /* TABLET (40) */
  {id:'TAB_01', cat:'Tablet', q:'Tablet won’t charge', a:'Check charger/port, try different cable, clean port and restart.', tags:['charging']},
  {id:'TAB_02', cat:'Tablet', q:'Tablet slow or laggy', a:'Close apps, clear storage, update OS, consider factory reset.', tags:['speed']},
  {id:'TAB_03', cat:'Tablet', q:'Screen cracked', a:'Avoid using with shards, back up data, replace screen assembly.', tags:['screen']},
  {id:'TAB_04', cat:'Tablet', q:'Wi-Fi keeps dropping', a:'Restart router/tablet, forget network, update firmware.', tags:['wifi']},
  {id:'TAB_05', cat:'Tablet', q:'Touchscreen ghost touches', a:'Remove protector, reboot, recalibrate if available, replace digitizer if persistent.', tags:['touch']},
  {id:'TAB_06', cat:'Tablet', q:'Apps won’t install', a:'Check storage and account settings, clear app store cache, retry.', tags:['apps']},
  {id:'TAB_07', cat:'Tablet', q:'Battery swollen', a:'Stop using, do not puncture, seek professional battery replacement.', tags:['battery']},
  {id:'TAB_08', cat:'Tablet', q:'Tablet won’t turn on', a:'Charge for 30 min, try different charger, force restart sequence.', tags:['power']},
  {id:'TAB_09', cat:'Tablet', q:'Audio not working', a:'Check volume, Bluetooth routing, test headphones and speaker.', tags:['audio']},
  {id:'TAB_10', cat:'Tablet', q:'Overheating during use', a:'Avoid heavy apps for long periods, remove case, update apps.', tags:['overheat']},
  {id:'TAB_11', cat:'Tablet', q:'Camera failing', a:'Restart app, clear camera cache, test with other apps, update OS.', tags:['camera']},
  {id:'TAB_12', cat:'Tablet', q:'Stylus not working', a:'Replace tip, pair again, charge stylus, check app settings.', tags:['stylus']},
  {id:'TAB_13', cat:'Tablet', q:'Screen dim/brightness issue', a:'Disable auto-brightness, update drivers/firmware, test brightness slider.', tags:['display']},
  {id:'TAB_14', cat:'Tablet', q:'Tablet freezes while gaming', a:'Lower graphics settings, close background apps, ensure temperature kept low.', tags:['gaming']},
  {id:'TAB_15', cat:'Tablet', q:'Bluetooth keyboard not pairing', a:'Put keyboard in pairing mode, remove old pairings, restart tablet.', tags:['bluetooth']},
  {id:'TAB_16', cat:'Tablet', q:'Storage full quickly', a:'Clear cache, uninstall unused apps, move media to cloud or SD card if possible.', tags:['storage']},
  {id:'TAB_17', cat:'Tablet', q:'Touch ID not recognized', a:'Re-enroll fingerprints, clean sensor and fingers.', tags:['security']},
  {id:'TAB_18', cat:'Tablet', q:'GPS inaccurate', a:'Enable high accuracy mode, calibrate compass, update maps.', tags:['gps']},
  {id:'TAB_19', cat:'Tablet', q:'Screen flicker', a:'Update OS, test safe mode, check for loose connectors (repair).', tags:['display']},
  {id:'TAB_20', cat:'Tablet', q:'Factory reset tips', a:'Back up data, sign out of accounts, ensure charged battery before resetting.', tags:['reset']},

  {id:'TAB_21', cat:'Tablet', q:'Tablet keeps restarting', a:'Check for faulty apps, firmware updates, and perform safe mode diagnostics.', tags:['reboot']},
  {id:'TAB_22', cat:'Tablet', q:'MicroSD not recognized', a:'Unmount and remount, try different adapter, format after backup.', tags:['sdcard']},
  {id:'TAB_23', cat:'Tablet', q:'Screen color off or tint', a:'Adjust color profile, disable night mode, update drivers.', tags:['display']},
  {id:'TAB_24', cat:'Tablet', q:'No sound from speakers', a:'Test with headphones, check system volume and app output.', tags:['audio']},
  {id:'TAB_25', cat:'Tablet', q:'Tablet overheating while charging', a:'Use original charger, remove case, avoid using heavy apps while charging.', tags:['charging','overheat']},
  {id:'TAB_26', cat:'Tablet', q:'App permissions not saving', a:'Reset app preferences, clear app data, update OS.', tags:['permissions']},
  {id:'TAB_27', cat:'Tablet', q:'Bluetooth audio cutting out', a:'Reduce distance, re-pair device, check for interference.', tags:['bluetooth']},
  {id:'TAB_28', cat:'Tablet', q:'Touchscreen calibration option missing', a:'Use manufacturer diagnostic tools or update firmware to restore calibration settings.', tags:['touch']},
  {id:'TAB_29', cat:'Tablet', q:'Split-screen not working', a:'Ensure OS supports split-screen, update apps and system.', tags:['multitask']},
  {id:'TAB_30', cat:'Tablet', q:'Auto-rotate not working', a:'Toggle rotation lock, recalibrate orientation sensor, restart.', tags:['display']},
  {id:'TAB_31', cat:'Tablet', q:'Cannot pair to car', a:'Clear old pairings, check car’s Bluetooth compatibility, update both firmwares.', tags:['car','bluetooth']},
  {id:'TAB_32', cat:'Tablet', q:'VPN disconnects frequently', a:'Try different server, check network stability, update VPN app.', tags:['vpn','network']},
  {id:'TAB_33', cat:'Tablet', q:'Adaptive brightness flickers', a:'Disable adaptive brightness and test; update display driver.', tags:['display']},
  {id:'TAB_34', cat:'Tablet', q:'Cannot access SD card apps', a:'Move apps to internal storage or reinstall with SD card mounted.', tags:['sdcard','apps']},
  {id:'TAB_35', cat:'Tablet', q:'Screen goes black during video', a:'Disable power saving during media, update video app.', tags:['video']},
  {id:'TAB_36', cat:'Tablet', q:'USB-C accessory not detected', a:'Try different cable, ensure OTG supported and enabled.', tags:['usb']},
  {id:'TAB_37', cat:'Tablet', q:'Tablet shows incorrect time', a:'Sync time with network, check time zone settings, restart.', tags:['time']},
  {id:'TAB_38', cat:'Tablet', q:'Battery percentage jumps', a:'Calibrate battery by full charge/discharge cycle, check battery health.', tags:['battery']},
  {id:'TAB_39', cat:'Tablet', q:'App keeps asking for updates', a:'Clear Play/App Store cache and data, sign out/in of account.', tags:['apps']},
  {id:'TAB_40', cat:'Tablet', q:'Stylus latency', a:'Update stylus firmware/driver, reduce screen effects, test on different app.', tags:['stylus','latency']},

  /* GOOGLE (40) */
  {id:'GGL_01', cat:'Google', q:'Android not updating', a:'Free storage, stable Wi-Fi, plug in charger, try manual OTA via vendor tool.', tags:['update']},
  {id:'GGL_02', cat:'Google', q:'Google Play errors', a:'Clear Play Store cache/data, sign out/in of Google account, update Play Services.', tags:['playstore']},
  {id:'GGL_03', cat:'Google', q:'Google Assistant not working', a:'Check mic permission, language, and Assistant settings; update Google app.', tags:['assistant']},
  {id:'GGL_04', cat:'Google', q:'Pixel camera crash', a:'Clear camera app cache, update firmware, use safe mode to test.', tags:['camera']},
  {id:'GGL_05', cat:'Google', q:'Battery optimization kills apps', a:'Disable aggressive battery optimizations for trusted apps.', tags:['battery']},
  {id:'GGL_06', cat:'Google', q:'Random reboots on Android', a:'Check for faulty apps, wipe cache partition, factory reset after backup.', tags:['reboot']},
  {id:'GGL_07', cat:'Google', q:'Slow Android after update', a:'Reboot multiple times, clear cache, wait until background optimizations finish.', tags:['performance']},
  {id:'GGL_08', cat:'Google', q:'Notification channel missing', a:'Open app notifications and enable desired channels per app.', tags:['notifications']},
  {id:'GGL_09', cat:'Google', q:'Android won’t recognize SD card', a:'Unmount/remount, reformat (backup first), test card on PC.', tags:['sdcard']},
  {id:'GGL_10', cat:'Google', q:'Fingerprint sensor not working', a:'Re-register prints, ensure finger/sensor clean, remove screen protector near sensor.', tags:['security']},
  {id:'GGL_11', cat:'Google', q:'Mobile data slow', a:'Toggle airplane mode, reset APN, check carrier issues, test SIM in another phone.', tags:['network']},
  {id:'GGL_12', cat:'Google', q:'Bluetooth audio out of sync', a:'Toggle aptX/AAC options (if available), reconnect, update firmware.', tags:['bluetooth']},
  {id:'GGL_13', cat:'Google', q:'Device not charging rapidly', a:'Use original charger, enable fast-charge option in settings, try different cable.', tags:['charging']},
  {id:'GGL_14', cat:'Google', q:'Screen burn-in on OLED', a:'Reduce brightness, use dark themes, use pixel refresher apps where available.', tags:['display']},
  {id:'GGL_15', cat:'Google', q:'USB accessory not detected', a:'Enable OTG in settings, try different adapter/cable, check accessory compatibility.', tags:['usb']},
  {id:'GGL_16', cat:'Google', q:'Keyboard typing lag', a:'Change keyboard app, clear keyboard app cache, update firmware.', tags:['keyboard']},
  {id:'GGL_17', cat:'Google', q:'Apps failing to update', a:'Check Play Store, remove and re-add Google account, clear Store cache.', tags:['playstore']},
  {id:'GGL_18', cat:'Google', q:'Screen timeout too short', a:'Adjust display sleep settings or adaptive display options.', tags:['display']},
  {id:'GGL_19', cat:'Google', q:'Cast not found on TV', a:'Ensure both devices on same network and same Wi-Fi band, reboot router and devices.', tags:['cast']},
  {id:'GGL_20', cat:'Google', q:'Factory image restore tips', a:'Back up data, download verified image/tool from vendor, follow instructions carefully.', tags:['recovery']},

  {id:'GGL_21', cat:'Google', q:'Google account locked', a:'Use account recovery flow, verify identity, check for suspicious activity.', tags:['account']},
  {id:'GGL_22', cat:'Google', q:'Play Store download stuck', a:'Clear Play Store and Play Services cache, reboot, check storage.', tags:['playstore']},
  {id:'GGL_23', cat:'Google', q:'Nearby Share not showing devices', a:'Enable Nearby Share, turn on Bluetooth & location, set visibility to everyone/contacts.', tags:['share']},
  {id:'GGL_24', cat:'Google', q:'Smart Lock not working', a:'Check Trusted Places/devices settings and ensure location accuracy.', tags:['security']},
  {id:'GGL_25', cat:'Google', q:'Pixel slow camera startup', a:'Clear camera app cache, disable excessive camera features, restart.', tags:['camera']},
  {id:'GGL_26', cat:'Google', q:'Doze mode killing background tasks', a:'Whitelist apps from battery optimization for critical background tasks.', tags:['battery']},
  {id:'GGL_27', cat:'Google', q:'Unable to change default apps', a:'Reset app preferences and set defaults again in Settings > Apps.', tags:['apps']},
  {id:'GGL_28', cat:'Google', q:'Digital Wellbeing blocks notifications', a:'Adjust Focus mode or Bedtime settings to allow essential notifications.', tags:['wellbeing']},
  {id:'GGL_29', cat:'Google', q:'Android Auto disconnects', a:'Update head unit firmware and phone app, use high-quality USB cable.', tags:['car','androidauto']},
  {id:'GGL_30', cat:'Google', q:'Screen casting lags', a:'Reduce network congestion, use 5GHz Wi-Fi and close other streaming apps.', tags:['cast','network']},
  {id:'GGL_31', cat:'Google', q:'Android File Transfer not detecting device', a:'Enable file transfer mode (MTP), use official cable and reinstall drivers.', tags:['usb']},
  {id:'GGL_32', cat:'Google', q:'OS feature missing after update', a:'Check device compatibility, read release notes, and ensure vendor patches applied.', tags:['update','features']},
  {id:'GGL_33', cat:'Google', q:'Notifications duplicated', a:'Check for multiple accounts or apps mirroring, clear cache, restart.', tags:['notifications']},
  {id:'GGL_34', cat:'Google', q:'App permissions reset after reboot', a:'Check enterprise or profile policies, update OS or remove conflicting apps.', tags:['permissions']},
  {id:'GGL_35', cat:'Google', q:'Mobile hotspot disconnects', a:'Check carrier limits, AP band, and disable battery saver.', tags:['hotspot']},
  {id:'GGL_36', cat:'Google', q:'Device shows incorrect battery estimate', a:'Calibrate battery or run diagnostics; update battery stats.', tags:['battery']},
  {id:'GGL_37', cat:'Google', q:'Unable to uninstall system updates', a:'Some updates cannot be reverted; consider factory reset after backup.', tags:['update']},
  {id:'GGL_38', cat:'Google', q:'Screen gestures not recognized', a:'Relearn gestures, update firmware, and test touchscreen responsiveness.', tags:['touch']},
  {id:'GGL_39', cat:'Google', q:'App permissions request loop', a:'Clear app data and cache, update app, reinstall if needed.', tags:['permissions']},
  {id:'GGL_40', cat:'Google', q:'Cannot use VoLTE', a:'Ensure carrier and plan support VoLTE, enable in mobile network settings.', tags:['network','volte']},

  /* PHONE (40) */
  {id:'PHN_01', cat:'Phone', q:'Phone won’t boot', a:'Try force restart, charge 15–30 minutes, boot to recovery and use repair tools.', tags:['boot']},
  {id:'PHN_02', cat:'Phone', q:'Cracked screen advice', a:'Back up immediately, avoid using cracked glass, replace screen assembly.', tags:['screen']},
  {id:'PHN_03', cat:'Phone', q:'Liquid damage steps', a:'Power off, remove SIM, dry with airflow and desiccants; avoid charging until dry.', tags:['water']},
  {id:'PHN_04', cat:'Phone', q:'Microphone not heard', a:'Check app permissions, test voice recorder, clean mic holes.', tags:['microphone']},
  {id:'PHN_05', cat:'Phone', q:'Phone hot during charge', a:'Use correct charger, remove case, avoid heavy use while charging.', tags:['overheat']},
  {id:'PHN_06', cat:'Phone', q:'Apps use too much data', a:'Restrict background data per app, use Wi-Fi for updates.', tags:['data']},
  {id:'PHN_07', cat:'Phone', q:'Unable to factory reset', a:'Use recovery mode or vendor PC tool; ensure credentials for FRP locks.', tags:['reset']},
  {id:'PHN_08', cat:'Phone', q:'SIM locked / PIN issues', a:'Enter correct PIN, use PUK code provided by carrier to unlock.', tags:['sim']},
  {id:'PHN_09', cat:'Phone', q:'Screen tint or color wrong', a:'Disable color filters, recalibrate display if available, update firmware.', tags:['display']},
  {id:'PHN_10', cat:'Phone', q:'Slow camera or app load', a:'Clear cache, free storage, close background processes.', tags:['camera']},
  {id:'PHN_11', cat:'Phone', q:'Phone vibrates but no ring', a:'Check Do Not Disturb and sound profile, test ringtone settings.', tags:['sound']},
  {id:'PHN_12', cat:'Phone', q:'Cellular data not working', a:'Reset APN settings, toggle airplane mode, reseat SIM, contact carrier.', tags:['network']},
  {id:'PHN_13', cat:'Phone', q:'Phone shows unknown charges', a:'Check app purchases, carrier bills, secure device and change passwords.', tags:['billing']},
  {id:'PHN_14', cat:'Phone', q:'Screen protector causing issues', a:'Remove protector and test; buy high-quality tempered glass.', tags:['accessory']},
  {id:'PHN_15', cat:'Phone', q:'Phone camera app shutter lag', a:'Clear camera cache, update app, test third-party camera.', tags:['camera']},
  {id:'PHN_16', cat:'Phone', q:'Unable to make calls', a:'Check signal, airplane mode, correct network mode and SIM placement.', tags:['calls']},
  {id:'PHN_17', cat:'Phone', q:'Slow app updates', a:'Restart device, clear Play/App Store cache, verify Wi-Fi speed.', tags:['update']},
  {id:'PHN_18', cat:'Phone', q:'Screen protector bubble removal', a:'Lift edge and reapply or replace with better alignment and dust-free environment.', tags:['screen']},
  {id:'PHN_19', cat:'Phone', q:'Phone camera not focusing', a:'Tap to focus, restart camera, update software; replace module if failing.', tags:['camera']},
  {id:'PHN_20', cat:'Phone', q:'Phone storage reporting wrong size', a:'Clear caches, remove large files, reboot; sometimes media scanning delays show wrong used space.', tags:['storage']},

  {id:'PHN_21', cat:'Phone', q:'NFC not working', a:'Ensure NFC enabled in settings, remove any case that blocks coil, restart device.', tags:['nfc']},
  {id:'PHN_22', cat:'Phone', q:'Notifications delayed', a:'Disable battery optimizations for the app, check background data, update app.', tags:['notifications']},
  {id:'PHN_23', cat:'Phone', q:'Phone keeps restarting', a:'Check for stuck power button, faulty app, or failing battery; safe mode helps isolate.', tags:['reboot']},
  {id:'PHN_24', cat:'Phone', q:'Cannot transfer contacts', a:'Use SIM export, cloud sync (Google/iCloud) or Bluetooth/third-party transfer tools.', tags:['contacts']},
  {id:'PHN_25', cat:'Phone', q:'Ringtone not playing for specific contact', a:'Check contact-specific tone, Do Not Disturb schedules, and app conflicts.', tags:['sound']},
  {id:'PHN_26', cat:'Phone', q:'Phone shows wrong carrier', a:'Update carrier settings, reseat SIM, check carrier provisioning.', tags:['carrier']},
  {id:'PHN_27', cat:'Phone', q:'Cannot connect to Wi-Fi 5GHz', a:'Check router band support, distance, and device compatibility.', tags:['wifi']},
  {id:'PHN_28', cat:'Phone', q:'Screen ghosting after long use', a:'Power cycle, reduce high-contrast content, contact vendor if persistent.', tags:['display']},
  {id:'PHN_29', cat:'Phone', q:'Voice over LTE (VoLTE) not available', a:'Enable VoLTE in network settings and verify carrier support.', tags:['network','volte']},
  {id:'PHN_30', cat:'Phone', q:'Phone overheating during calls', a:'Check signal strength, reduce background apps, avoid heavy network usage during calls.', tags:['overheat']},
  {id:'PHN_31', cat:'Phone', q:'Speakerphone low volume', a:'Check speaker grill, disable Bluetooth, test call with headphones.', tags:['audio']},
  {id:'PHN_32', cat:'Phone', q:'Cannot pair Bluetooth headset', a:'Clear pairing list, set headset to pairing mode, update firmware.', tags:['bluetooth']},
  {id:'PHN_33', cat:'Phone', q:'App permissions prompt not showing', a:'Reset app preferences or reinstall app, check system-level permission controls.', tags:['permissions']},
  {id:'PHN_34', cat:'Phone', q:'Phone won’t charge wirelessly', a:'Ensure coil alignment, remove metal case, confirm wireless charger compatibility.', tags:['charging','wireless']},
  {id:'PHN_35', cat:'Phone', q:'Phone camera lens scratched', a:'Use protective lens or replace camera glass; back up data before repairs.', tags:['camera','repair']},
  {id:'PHN_36', cat:'Phone', q:'System update failed repeatedly', a:'Clear update cache, ensure battery >50%, use vendor recovery tools.', tags:['update']},
  {id:'PHN_37', cat:'Phone', q:'Phone not recognized by PC', a:'Enable USB debugging (if needed), select file transfer (MTP) mode, try different cable.', tags:['usb']},
  {id:'PHN_38', cat:'Phone', q:'Mobile hotspot slow', a:'Limit connected devices, check upstream connection, use 5GHz hotspot if available.', tags:['hotspot']},
  {id:'PHN_39', cat:'Phone', q:'Cannot record calls', a:'Check local laws and OS restrictions; use approved apps or external recorder.', tags:['calls','recording']},
  {id:'PHN_40', cat:'Phone', q:'Phone stuck in headphone mode', a:'Plug/unplug headphones several times, clean headphone jack, restart device.', tags:['audio']},

  /* DRONE (40) */
  {id:'DRN_01', cat:'Drone', q:'Drone won’t take off', a:'Check battery charge, ensure props installed correctly and not damaged, verify motors spin in motor test, and confirm firmware is up to date.', tags:['flight']},
  {id:'DRN_02', cat:'Drone', q:'Drone GPS not locking', a:'Move to an open area with a clear sky, restart the drone and controller, wait for a full GPS lock before takeoff, and recalibrate the compass if needed.', tags:['gps']},
  {id:'DRN_03', cat:'Drone', q:'Drone drifting in hover', a:'Calibrate the IMU and compass, ensure the home point is set correctly, check for bent props or motor issues, and perform a test hover at low altitude.', tags:['drift','calibration']},
  {id:'DRN_04', cat:'Drone', q:'Propeller damaged', a:'Replace cracked or chipped propellers with manufacturer-approved spares and ensure each prop is installed in the correct orientation.', tags:['propeller']},
  {id:'DRN_05', cat:'Drone', q:'Controller not binding', a:'Follow the manufacturer binding procedure, ensure both devices are charged, and confirm firmware versions are compatible before retrying the bind.', tags:['pairing']},
  {id:'DRN_06', cat:'Drone', q:'Drone loses video feed', a:'Reduce distance, check antenna alignment on both drone and controller, update transmitter/receiver firmware, and test with another device to isolate the issue.', tags:['video','transmission']},
  {id:'DRN_07', cat:'Drone', q:'Battery swelling', a:'Stop using a swollen battery immediately, dispose of it safely per local regulations, and replace with a healthy battery from a trusted source.', tags:['battery','safety']},
  {id:'DRN_08', cat:'Drone', q:'Motors making unusual noise', a:'Inspect motors for debris, check motor bearings, ensure props are tight and not rubbing the frame; replace motors if bearings are failing.', tags:['motor']},
  {id:'DRN_09', cat:'Drone', q:'Failsafe return-to-home triggers unexpectedly', a:'Check GPS and compass status before flight, set a safe RTH altitude, verify GPS lock, and ensure no geofencing or firmware restrictions are active.', tags:['rth','gps']},
  {id:'DRN_10', cat:'Drone', q:'Firmware update failed', a:'Ensure batteries are fully charged, use a stable internet connection, follow vendor recovery steps if update fails, and retry the process.', tags:['firmware']},
  {id:'DRN_11', cat:'Drone', q:'Gimbal not stabilizing', a:'Check gimbal mounting screws, balance the camera payload, recalibrate gimbal in the app, and update gimbal firmware if available.', tags:['gimbal']},
  {id:'DRN_12', cat:'Drone', q:'Remote control range reduced', a:'Verify antenna orientation, avoid areas with RF interference, update firmware, and test with different locations to isolate interference sources.', tags:['range','antenna']},
  {id:'DRN_13', cat:'Drone', q:'SD card not recording', a:'Use recommended speed-class cards, format the card in the drone, ensure it’s seated correctly, and try a different card to rule out media failure.', tags:['storage','sd']},
  {id:'DRN_14', cat:'Drone', q:'Calibration errors persist', a:'Place the drone on a flat, level surface, remove propellers if instructed, follow the exact manufacturer steps for IMU and compass calibration, and avoid nearby metal objects.', tags:['calibration']},
  {id:'DRN_15', cat:'Drone', q:'Drone won’t arm', a:'Check preflight conditions (GPS lock, battery level, prop guards removed), ensure geofence or flight restrictions aren’t blocking arming, and consult the app status messages for specific errors.', tags:['arming']},
  {id:'DRN_16', cat:'Drone', q:'Telemetry disconnects intermittently', a:'Inspect antenna connections, reduce obstructions between controller and drone, avoid high-interference areas, and update radio firmware.', tags:['telemetry']},
  {id:'DRN_17', cat:'Drone', q:'Drone flips or tumbles at takeoff', a:'Immediately land if safe, inspect prop orientation and tightness, check motor direction and ESC wiring, and verify flight controller mounting and PID settings.', tags:['flight','safety']},
  {id:'DRN_18', cat:'Drone', q:'ESC / motor error shown in app', a:'Power off and replug battery, check motor and ESC connections, update ESC firmware, and replace any ESC or motor that shows hardware faults.', tags:['esc','motor']},
  {id:'DRN_19', cat:'Drone', q:'Camera tilt or gimbal stuck', a:'Power-cycle the drone, recalibrate the gimbal through the app, check for physical obstructions, and inspect gimbal cables for damage.', tags:['gimbal','camera']},
  {id:'DRN_20', cat:'Drone', q:'No live view on mobile app', a:'Confirm the camera stream settings, reconnect phone to controller Wi-Fi or proxy, ensure app permissions are granted, and update both app and drone firmware.', tags:['video','app']},

  {id:'DRN_21', cat:'Drone', q:'Compass interference alert', a:'Fly away from metal structures, recalibrate compass, and avoid vehicle roofs or large metal objects.', tags:['compass']},
  {id:'DRN_22', cat:'Drone', q:'Battery not charging fully', a:'Check charger output, battery connectors, balance leads, and replace if cells degrade.', tags:['battery','charging']},
  {id:'DRN_23', cat:'Drone', q:'Landing gear damaged', a:'Replace landing gear, inspect frame for stress fractures before next flight.', tags:['landing']},
  {id:'DRN_24', cat:'Drone', q:'Prop wash instability', a:'Adjust flight controls or PID tuning, avoid strong gusts, and check propellers for damage.', tags:['flight','tuning']},
  {id:'DRN_25', cat:'Drone', q:'Cannot enter sport mode', a:'Check geofence and flight mode locks, ensure firmware matches controller settings.', tags:['modes']},
  {id:'DRN_26', cat:'Drone', q:'Compass calibration fails', a:'Move away from metal, ensure drone is level, follow manufacturer sequence precisely.', tags:['calibration']},
  {id:'DRN_27', cat:'Drone', q:'Remote telemetry shows wrong altitude', a:'Verify barometer calibration, update firmware, and check GPS signal quality.', tags:['altitude','sensors']},
  {id:'DRN_28', cat:'Drone', q:'Loss of yaw control', a:'Inspect yaw motor ESC, recalibrate IMU, verify transmitter mixing and endpoints.', tags:['control']},
  {id:'DRN_29', cat:'Drone', q:'Failsafe RC channel stick drift', a:'Center trims, recalibrate controller sticks, replace gimbals if worn.', tags:['controller']},
  {id:'DRN_30', cat:'Drone', q:'Video recording stops unexpectedly', a:'Check SD card health/class, file system errors, and app crash reports.', tags:['video','storage']},
  {id:'DRN_31', cat:'Drone', q:'Firmware mismatched between modules', a:'Update all components to matching firmware versions using official tools.', tags:['firmware']},
  {id:'DRN_32', cat:'Drone', q:'Frame cracks after crash', a:'Inspect structure, replace affected arms or frame components before flying.', tags:['repair']},
  {id:'DRN_33', cat:'Drone', q:'Gimbal motor overloaded', a:'Reduce camera weight, rebalance payload, and check motor torque limits.', tags:['gimbal']},
  {id:'DRN_34', cat:'Drone', q:'Drone won’t connect to app', a:'Clear app cache, try another device, ensure both on same Wi-Fi or direct connection.', tags:['app','connection']},
  {id:'DRN_35', cat:'Drone', q:'Propeller screws keep loosening', a:'Use threadlocker per manufacturer spec, check torque and replace stripped screws.', tags:['maintenance']},
  {id:'DRN_36', cat:'Drone', q:'Battery shows negative voltage', a:'Stop using battery, store safely, and dispose/recycle following regulations.', tags:['battery','safety']},
  {id:'DRN_37', cat:'Drone', q:'RC sticks not centered in app', a:'Calibrate transmitter, check trim settings, and replace stick modules if worn.', tags:['controller']},
  {id:'DRN_38', cat:'Drone', q:'Compass offset changes with payload', a:'Recalibrate compass with payload attached or remove magnetic components.', tags:['compass','payload']},
  {id:'DRN_39', cat:'Drone', q:'Drone loses altitude hold', a:'Check barometer and optical flow sensors, clean sensors and recalibrate.', tags:['altitude','sensors']},
  {id:'DRN_40', cat:'Drone', q:'Cannot flash firmware', a:'Use official flashing tools, correct firmware file, and ensure stable USB connection.', tags:['firmware','flash']},

  /* DESKTOP (40) */
  {id:'DSK_01', cat:'Desktop', q:'Desktop won’t power on', a:'Check power cable, PSU switch, reseat RAM and cables.', tags:['power']},
  {id:'DSK_02', cat:'Desktop', q:'No display signal', a:'Check monitor cable, GPU seated, try onboard graphics.', tags:['display']},
  {id:'DSK_03', cat:'Desktop', q:'Boot device not found', a:'Check BIOS boot order, reseat or replace SSD/HDD.', tags:['boot']},
  {id:'DSK_04', cat:'Desktop', q:'Fan noisy', a:'Clean dust, replace worn bearings, ensure fans not hitting cables.', tags:['fan']},
  {id:'DSK_05', cat:'Desktop', q:'Overheating CPU', a:'Reapply thermal paste, clean heatsink, check fan curve.', tags:['temperature']},
  {id:'DSK_06', cat:'Desktop', q:'USB ports not working', a:'Check BIOS settings, reinstall chipset drivers.', tags:['usb']},
  {id:'DSK_07', cat:'Desktop', q:'System freezes randomly', a:'Check RAM stability, PSU quality, update BIOS.', tags:['freeze']},
  {id:'DSK_08', cat:'Desktop', q:'Blue screen errors', a:'Note error code, update drivers, run memory diagnostic.', tags:['bsod']},
  {id:'DSK_09', cat:'Desktop', q:'No internet connection', a:'Check Ethernet cable, driver status, IP config.', tags:['network']},
  {id:'DSK_10', cat:'Desktop', q:'Slow startup', a:'Disable startup apps, switch HDD to SSD.', tags:['performance']},
  {id:'DSK_11', cat:'Desktop', q:'Keyboard not detected', a:'Plug into another port, replace keyboard, reset BIOS.', tags:['keyboard']},
  {id:'DSK_12', cat:'Desktop', q:'GPU overheating', a:'Clean fans, adjust airflow, repaste GPU.', tags:['gpu']},
  {id:'DSK_13', cat:'Desktop', q:'Audio crackling', a:'Update sound driver, test other audio outputs.', tags:['audio']},
  {id:'DSK_14', cat:'Desktop', q:'CMOS reset needed', a:'Remove battery 5 min, reinsert, reset time/date.', tags:['bios']},
  {id:'DSK_15', cat:'Desktop', q:'No POST beep', a:'Check speaker connection, verify RAM/GPU seated.', tags:['post']},
  {id:'DSK_16', cat:'Desktop', q:'LAN port light off', a:'Test other cable, enable LAN in BIOS.', tags:['network']},
  {id:'DSK_17', cat:'Desktop', q:'PC restarts itself', a:'Check PSU wattage, update BIOS, check overheating.', tags:['power']},
  {id:'DSK_18', cat:'Desktop', q:'SSD not detected', a:'Reconnect SATA cable, update BIOS firmware.', tags:['storage']},
  {id:'DSK_19', cat:'Desktop', q:'Mouse lag', a:'Use USB 2.0 port, clean sensor, check surface.', tags:['mouse']},
  {id:'DSK_20', cat:'Desktop', q:'Windows activation lost', a:'Sign into Microsoft account, run activation troubleshooter.', tags:['windows']},

  {id:'DSK_21', cat:'Desktop', q:'Power button unresponsive', a:'Check front panel connectors, test with PSU paperclip to isolate.', tags:['power']},
  {id:'DSK_22', cat:'Desktop', q:'BIOS won’t save settings', a:'Reset CMOS, update BIOS, check battery voltage.', tags:['bios']},
  {id:'DSK_23', cat:'Desktop', q:'Peripheral intermittently disconnects', a:'Try different USB header, update drivers, replace cable.', tags:['usb','peripheral']},
  {id:'DSK_24', cat:'Desktop', q:'PCIe device not recognized', a:'Reseat card, update chipset/GPU drivers, check BIOS lane settings.', tags:['pcie']},
  {id:'DSK_25', cat:'Desktop', q:'Strange POST codes', a:'Consult motherboard manual, reseat components, isolate faulty part.', tags:['post']},
  {id:'DSK_26', cat:'Desktop', q:'Slow disk performance', a:'Check SMART, run disk benchmark, update storage controller drivers.', tags:['storage']},
  {id:'DSK_27', cat:'Desktop', q:'RGB controller not responding', a:'Reinstall RGB software, check USB header and power connectors.', tags:['rgb']},
  {id:'DSK_28', cat:'Desktop', q:'Cannot install OS from USB', a:'Check boot mode (UEFI/Legacy), recreate bootable media, verify ISO.', tags:['install']},
  {id:'DSK_29', cat:'Desktop', q:'Integrated graphics disabled', a:'Enable iGPU in BIOS when no GPU present or for hybrid setups.', tags:['display']},
  {id:'DSK_30', cat:'Desktop', q:'Strange coil whine', a:'Try different PSU or GPU, reduce load or enable FPS cap to mitigate.', tags:['noise']},
  {id:'DSK_31', cat:'Desktop', q:'Windows corruption errors', a:'Run SFC /scannow, DISM repair, or repair install.', tags:['windows']},
  {id:'DSK_32', cat:'Desktop', q:'Multiple monitors flicker', a:'Check cables, refresh rates, GPU drivers, and monitor firmware.', tags:['display']},
  {id:'DSK_33', cat:'Desktop', q:'PSU making noise', a:'Check fan bearings, cable contact, replace PSU if failing.', tags:['power','psu']},
  {id:'DSK_34', cat:'Desktop', q:'Cannot update GPU driver', a:'Use DDU to clean old drivers, then install latest drivers from vendor.', tags:['gpu','drivers']},
  {id:'DSK_35', cat:'Desktop', q:'Bluetooth dongle unstable', a:'Try different USB port, update Bluetooth stack/drivers.', tags:['bluetooth']},
  {id:'DSK_36', cat:'Desktop', q:'Heat buildup in case', a:'Improve airflow, add intake/exhaust fans, tidy cables for better flow.', tags:['temperature']},
  {id:'DSK_37', cat:'Desktop', q:'Virtualization not available', a:'Enable VT-x/AMD-V in BIOS and update BIOS if option missing.', tags:['virtualization']},
  {id:'DSK_38', cat:'Desktop', q:'Drive encryption issues', a:'Ensure key backups, verify TPM status, check BitLocker policies.', tags:['security']},
  {id:'DSK_39', cat:'Desktop', q:'RGB sync mismatch across apps', a:'Use single vendor control app or sync protocol, update firmware.', tags:['rgb']},
  {id:'DSK_40', cat:'Desktop', q:'Cannot wake from sleep', a:'Check device power settings, update drivers, disable fast startup.', tags:['sleep']},

  /* LAPTOP (40) */
  {id:'LAP_01', cat:'Laptop', q:'Laptop not charging', a:'Check charger/port, battery health, update BIOS.', tags:['charging']},
  {id:'LAP_02', cat:'Laptop', q:'Battery drains fast', a:'Lower brightness, close apps, use battery saver.', tags:['battery']},
  {id:'LAP_03', cat:'Laptop', q:'Overheating', a:'Clean fans, use cooling pad, repaste CPU/GPU.', tags:['temperature']},
  {id:'LAP_04', cat:'Laptop', q:'Keyboard not typing', a:'Check for stuck keys, reinstall drivers, external test.', tags:['keyboard']},
  {id:'LAP_05', cat:'Laptop', q:'Touchpad not working', a:'Enable in settings, update driver, check Fn key toggle.', tags:['touchpad']},
  {id:'LAP_06', cat:'Laptop', q:'Display flickering', a:'Update GPU driver, change refresh rate, test safe mode.', tags:['display']},
  {id:'LAP_07', cat:'Laptop', q:'Wi-Fi dropping', a:'Reinstall driver, reset network stack, toggle airplane mode.', tags:['wifi']},
  {id:'LAP_08', cat:'Laptop', q:'Audio not working', a:'Select correct output, reinstall driver, test headphones.', tags:['audio']},
  {id:'LAP_09', cat:'Laptop', q:'USB port dead', a:'Check power management USB suspend settings.', tags:['usb']},
  {id:'LAP_10', cat:'Laptop', q:'Webcam not detected', a:'Enable in BIOS, reinstall camera driver.', tags:['camera']},
  {id:'LAP_11', cat:'Laptop', q:'No boot device', a:'Check boot order, reinstall OS, test drive.', tags:['boot']},
  {id:'LAP_12', cat:'Laptop', q:'Fan noise', a:'Clean vents, adjust fan curve, replace faulty fan.', tags:['fan']},
  {id:'LAP_13', cat:'Laptop', q:'Trackpad gesture fail', a:'Update precision driver, re-enable gestures.', tags:['touchpad']},
  {id:'LAP_14', cat:'Laptop', q:'Battery not detected', a:'Disconnect AC, hold power 30s, reconnect battery.', tags:['battery']},
  {id:'LAP_15', cat:'Laptop', q:'HDMI not working', a:'Reconnect cable, change display mode (Win+P).', tags:['display']},
  {id:'LAP_16', cat:'Laptop', q:'Slow performance', a:'Disable startup apps, upgrade to SSD, add RAM.', tags:['performance']},
  {id:'LAP_17', cat:'Laptop', q:'Touchscreen not responding', a:'Recalibrate, update HID driver.', tags:['touch']},
  {id:'LAP_18', cat:'Laptop', q:'Blue screen errors', a:'Update drivers, check RAM, run system file check.', tags:['bsod']},
  {id:'LAP_19', cat:'Laptop', q:'Sleep mode issues', a:'Change power plan, update BIOS, disable hybrid sleep.', tags:['sleep']},
  {id:'LAP_20', cat:'Laptop', q:'Overcharge protection', a:'Enable battery care mode if available.', tags:['battery']},

  {id:'LAP_21', cat:'Laptop', q:'Laptop keyboard backlight not working', a:'Toggle keyboard backlight key, update drivers, check BIOS setting.', tags:['keyboard','backlight']},
  {id:'LAP_22', cat:'Laptop', q:'Laptop lid sensor broken', a:'Disable lid sleep behavior in power settings, replace sensor if needed.', tags:['lid']},
  {id:'LAP_23', cat:'Laptop', q:'Microphone low sensitivity', a:'Adjust recording levels, test with external mic and check privacy settings.', tags:['microphone']},
  {id:'LAP_24', cat:'Laptop', q:'Unable to connect to docking station', a:'Update Thunderbolt/USB-C drivers and firmware, test cable and port.', tags:['docking']},
  {id:'LAP_25', cat:'Laptop', q:'Keyboard letters duplicated', a:'Check for stuck keys, malware, or driver issues; try external keyboard.', tags:['keyboard']},
  {id:'LAP_26', cat:'Laptop', q:'Battery not lasting as rated', a:'Calibrate battery, lower performance mode, check background tasks.', tags:['battery','performance']},
  {id:'LAP_27', cat:'Laptop', q:'Cannot detect second monitor', a:'Update display drivers, check cable/adapter, set correct input.', tags:['display']},
  {id:'LAP_28', cat:'Laptop', q:'Fingerprint reader fails', a:'Re-enroll fingerprint, update drivers, clean sensor.', tags:['security']},
  {id:'LAP_29', cat:'Laptop', q:'Laptop smells of burning', a:'Power off immediately, inspect vents and components for dust or short.', tags:['safety']},
  {id:'LAP_30', cat:'Laptop', q:'Touchpad moves cursor erratically', a:'Disable touchpad while typing feature, update driver, check for dirt.', tags:['touchpad']},
  {id:'LAP_31', cat:'Laptop', q:'Laptop display has dead pixels', a:'Use dead pixel tools to detect, contact warranty if enough pixels affected.', tags:['display']},
  {id:'LAP_32', cat:'Laptop', q:'Laptop speakers distorted at high volume', a:'Update audio drivers, disable audio enhancements, test external speakers.', tags:['audio']},
  {id:'LAP_33', cat:'Laptop', q:'Never-ending Windows updates', a:'Run Windows Update troubleshooter, clear update cache.', tags:['windows','update']},
  {id:'LAP_34', cat:'Laptop', q:'Laptop hinge loose', a:'Tighten hinge screws or replace hinge assembly carefully.', tags:['repair']},
  {id:'LAP_35', cat:'Laptop', q:'Ethernet port not working', a:'Check driver, test cable, disable power saving for NIC.', tags:['network']},
  {id:'LAP_36', cat:'Laptop', q:'Cannot boot into BIOS', a:'Use emergency BIOS recovery keys or remove battery to reset.', tags:['bios']},
  {id:'LAP_37', cat:'Laptop', q:'Battery charges to 100% then drops quickly', a:'Check battery health, replace battery if cells failing.', tags:['battery']},
  {id:'LAP_38', cat:'Laptop', q:'Laptop camera grainy in low light', a:'Increase exposure in app, enable low-light mode, add lighting.', tags:['camera']},
  {id:'LAP_39', cat:'Laptop', q:'Laptop won’t recognize SSD after cloning', a:'Check partition alignment, ensure SATA/NVMe driver support, re-seat drive.', tags:['storage']},
  {id:'LAP_40', cat:'Laptop', q:'Unable to disable integrated GPU', a:'Some systems lock iGPU; update BIOS and check hybrid graphics settings.', tags:['gpu']},

  /* WATCH (40) */
  {id:'WCH_01', cat:'Watch', q:'Watch not turning on', a:'Charge for at least 30 minutes, try reset sequence.', tags:['power']},
  {id:'WCH_02', cat:'Watch', q:'Watch not syncing', a:'Toggle Bluetooth, reopen app, restart both devices.', tags:['sync']},
  {id:'WCH_03', cat:'Watch', q:'Step count inaccurate', a:'Tighten strap, calibrate motion sensors.', tags:['sensor']},
  {id:'WCH_04', cat:'Watch', q:'Battery draining fast', a:'Reduce brightness, disable always-on display.', tags:['battery']},
  {id:'WCH_05', cat:'Watch', q:'Heart rate sensor not reading', a:'Clean underside, tighten band, restart device.', tags:['sensor']},
  {id:'WCH_06', cat:'Watch', q:'App notifications missing', a:'Enable app access in wearable app settings.', tags:['notifications']},
  {id:'WCH_07', cat:'Watch', q:'Watch overheats', a:'Remove from wrist, close apps, update firmware.', tags:['heat']},
  {id:'WCH_08', cat:'Watch', q:'Touchscreen lag', a:'Reboot, reduce animations, clear cache.', tags:['touch']},
  {id:'WCH_09', cat:'Watch', q:'Display dim outdoors', a:'Enable auto-brightness or raise brightness manually.', tags:['display']},
  {id:'WCH_10', cat:'Watch', q:'Charging cradle not connecting', a:'Clean contacts, use OEM charger.', tags:['charging']},
  {id:'WCH_11', cat:'Watch', q:'Time not accurate', a:'Sync with phone or internet time server.', tags:['time']},
  {id:'WCH_12', cat:'Watch', q:'Firmware update failed', a:'Retry with enough battery and Wi-Fi.', tags:['firmware']},
  {id:'WCH_13', cat:'Watch', q:'Strap sensor error', a:'Clean contacts, reconnect strap.', tags:['sensor']},
  {id:'WCH_14', cat:'Watch', q:'Screen cracked', a:'Replace screen via authorized service.', tags:['screen']},
  {id:'WCH_15', cat:'Watch', q:'No vibration alerts', a:'Check vibration intensity settings.', tags:['vibration']},
  {id:'WCH_16', cat:'Watch', q:'Watch not pairing', a:'Reset Bluetooth pair list and retry.', tags:['bluetooth']},
  {id:'WCH_17', cat:'Watch', q:'GPS off-track', a:'Enable high accuracy, update AGPS data.', tags:['gps']},
  {id:'WCH_18', cat:'Watch', q:'Charging slow', a:'Try different adapter, clean contacts.', tags:['charging']},
  {id:'WCH_19', cat:'Watch', q:'Voice assistant not responding', a:'Reconnect to phone, check microphone permissions.', tags:['assistant']},
  {id:'WCH_20', cat:'Watch', q:'Water detected alert stuck', a:'Dry watch, restart, toggle water ejection mode.', tags:['water']},

  {id:'WCH_21', cat:'Watch', q:'Watch keeps restarting', a:'Factory reset after backup, ensure apps updated.', tags:['reboot']},
  {id:'WCH_22', cat:'Watch', q:'Sleep tracking inaccurate', a:'Wear snugly, ensure latest firmware, calibrate sleep settings.', tags:['health']},
  {id:'WCH_23', cat:'Watch', q:'Cannot install watch faces', a:'Check compatibility, update companion app, free storage.', tags:['watchfaces']},
  {id:'WCH_24', cat:'Watch', q:'Companion app crashes', a:'Clear app cache, reinstall app, update phone OS.', tags:['app']},
  {id:'WCH_25', cat:'Watch', q:'Bluetooth range short', a:'Avoid obstructions, ensure Bluetooth not limited by phone settings.', tags:['bluetooth']},
  {id:'WCH_26', cat:'Watch', q:'Touchscreen has dead zones', a:'Restart device, update firmware, contact service if hardware.', tags:['touch']},
  {id:'WCH_27', cat:'Watch', q:'Watch stuck in headphone mode', a:'Disconnect audio devices, restart, check media output settings.', tags:['audio']},
  {id:'WCH_28', cat:'Watch', q:'Cannot make or receive calls', a:'Check cellular plan (for LTE models), signal and companion settings.', tags:['calls']},
  {id:'WCH_29', cat:'Watch', q:'Watch face widget not updating', a:'Open host app, ensure background refresh enabled.', tags:['widgets']},
  {id:'WCH_30', cat:'Watch', q:'ECG app not available', a:'ECG availability depends on region and device; update firmware and app.', tags:['health','ecg']},
  {id:'WCH_31', cat:'Watch', q:'Watch lags after update', a:'Wait for post-update optimizations or perform factory reset.', tags:['performance']},
  {id:'WCH_32', cat:'Watch', q:'Heart rate always high', a:'Check strap fit, update firmware, consult medical if persistent.', tags:['health']},
  {id:'WCH_33', cat:'Watch', q:'Cannot reply to messages', a:'Check input methods availability and companion app permissions.', tags:['messages']},
  {id:'WCH_34', cat:'Watch', q:'Watch not receiving OTA', a:'Ensure phone and watch connected, enough battery and Wi-Fi.', tags:['firmware']},
  {id:'WCH_35', cat:'Watch', q:'Screen burns after long display', a:'Enable always-on dim mode, reduce brightness to prevent burn.', tags:['display']},
  {id:'WCH_36', cat:'Watch', q:'Watch shows incorrect steps after gym', a:'Disable wrist detection during certain activities or recalibrate sensors.', tags:['sensor']},
  {id:'WCH_37', cat:'Watch', q:'Watch mic picks up static', a:'Restart device, check for water ingress, update firmware.', tags:['microphone']},
  {id:'WCH_38', cat:'Watch', q:'Charging puck magnet weak', a:'Clean contacts, ensure correct alignment and replace puck if worn.', tags:['charging']},
  {id:'WCH_39', cat:'Watch', q:'Cannot add cards to wallet', a:'Region/payment method restrictions apply; update app and OS.', tags:['wallet']},
  {id:'WCH_40', cat:'Watch', q:'Watch stuck during factory reset', a:'Let battery drain then recharge and retry; contact support if stuck.', tags:['reset']},

  /* GAMING (40) */
  {id:'GME_01', cat:'Gaming', q:'Console not powering', a:'Check power cable, surge protector, reset PSU.', tags:['power']},
  {id:'GME_02', cat:'Gaming', q:'Controller drift', a:'Clean analog stick, recalibrate, replace module.', tags:['controller']},
  {id:'GME_03', cat:'Gaming', q:'No video signal', a:'Check HDMI port and cable, set correct input.', tags:['display']},
  {id:'GME_04', cat:'Gaming', q:'Game freezes', a:'Restart system, clear cache, reinstall game.', tags:['crash']},
  {id:'GME_05', cat:'Gaming', q:'Slow downloads', a:'Pause/resume download, use wired connection.', tags:['network']},
  {id:'GME_06', cat:'Gaming', q:'Overheating console', a:'Clean vents, elevate console, ensure airflow.', tags:['heat']},
  {id:'GME_07', cat:'Gaming', q:'No sound in game', a:'Check output device, HDMI audio, and console sound settings.', tags:['audio']},
  {id:'GME_08', cat:'Gaming', q:'Disc not reading', a:'Clean disc, update firmware, test another disc.', tags:['disc']},
  {id:'GME_09', cat:'Gaming', q:'Cannot connect online', a:'Test internet connection, check NAT type.', tags:['online']},
  {id:'GME_10', cat:'Gaming', q:'Lag during online play', a:'Use wired Ethernet, close background downloads.', tags:['network']},
  {id:'GME_11', cat:'Gaming', q:'Save data lost', a:'Enable cloud sync, back up regularly.', tags:['save']},
  {id:'GME_12', cat:'Gaming', q:'Controller won’t connect', a:'Pair again, reset controller, update firmware.', tags:['controller']},
  {id:'GME_13', cat:'Gaming', q:'Console crashes on startup', a:'Boot in safe mode, rebuild database.', tags:['boot']},
  {id:'GME_14', cat:'Gaming', q:'Fan too loud', a:'Clean dust, ensure console not enclosed.', tags:['fan']},
  {id:'GME_15', cat:'Gaming', q:'Account login issue', a:'Reset password, verify email, check server status.', tags:['account']},
  {id:'GME_16', cat:'Gaming', q:'Storage full', a:'Delete unused games, move to external drive.', tags:['storage']},
  {id:'GME_17', cat:'Gaming', q:'Update fails', a:'Restart console, check internet, retry.', tags:['update']},
  {id:'GME_18', cat:'Gaming', q:'Game won’t install', a:'Clear cache, ensure storage free, reinstall.', tags:['install']},
  {id:'GME_19', cat:'Gaming', q:'Console not detecting controller', a:'Use USB pairing, replace cable.', tags:['controller']},
  {id:'GME_20', cat:'Gaming', q:'No internet after update', a:'Reset network settings, reboot router.', tags:['network']},

  {id:'GME_21', cat:'Gaming', q:'HDR not working', a:'Enable HDR in console and TV settings, use HDMI 2.0+ cable.', tags:['display','hdr']},
  {id:'GME_22', cat:'Gaming', q:'Console shows error code', a:'Note code and consult vendor support or perform suggested troubleshoot.', tags:['error']},
  {id:'GME_23', cat:'Gaming', q:'Controller battery drains quickly', a:'Replace battery pack, disable vibration or background pairing.', tags:['battery','controller']},
  {id:'GME_24', cat:'Gaming', q:'Remote play connection issue', a:'Check port forwarding, internet speed and NAT type, update apps.', tags:['remote']},
  {id:'GME_25', cat:'Gaming', q:'Voice chat not heard', a:'Check party/party privacy settings, mic mute, and network quality.', tags:['chat','voice']},
  {id:'GME_26', cat:'Gaming', q:'Game lags only in multiplayer', a:'Server-side issues possible—test local network, use wired connection.', tags:['network']},
  {id:'GME_27', cat:'Gaming', q:'Controller lights flashing', a:'Indicates pairing or error—re-pair and check battery/firmware.', tags:['controller']},
  {id:'GME_28', cat:'Gaming', q:'Console storage slow after expansion', a:'Format external drive correctly and use USB 3.0/3.1 ports.', tags:['storage']},
  {id:'GME_29', cat:'Gaming', q:'Save file corrupted after crash', a:'Restore from cloud save or use backups if available.', tags:['save']},
  {id:'GME_30', cat:'Gaming', q:'Cannot change account region', a:'Region locked content and purchases may prevent changes; check vendor policy.', tags:['account','region']},
  {id:'GME_31', cat:'Gaming', q:'Screen tearing on console', a:'Enable V-sync/VRR support on TV or change display mode.', tags:['display']},
  {id:'GME_32', cat:'Gaming', q:'Game stuck on update loop', a:'Delete update, clear cache, re-download or reinstall game.', tags:['update']},
  {id:'GME_33', cat:'Gaming', q:'Console disc eject stuck', a:'Power cycle, use manual eject hole or seek repair for mechanical fault.', tags:['disc']},
  {id:'GME_34', cat:'Gaming', q:'Controller not charging', a:'Check charging dock/cable and controller port, replace battery if needed.', tags:['controller','charging']},
  {id:'GME_35', cat:'Gaming', q:'Controller button unresponsive', a:'Repair by cleaning contacts or replace button module.', tags:['controller','repair']},
  {id:'GME_36', cat:'Gaming', q:'Console overheating in enclosed space', a:'Provide ventilation, avoid stacking devices, use stand for airflow.', tags:['heat']},
  {id:'GME_37', cat:'Gaming', q:'Game voice language not available', a:'Check game language packs and region availability.', tags:['language']},
  {id:'GME_38', cat:'Gaming', q:'Controller firmware update stuck', a:'Restart console and controller, try alternative update method.', tags:['controller','firmware']},
  {id:'GME_39', cat:'Gaming', q:'Online friend list not updating', a:'Check server status and refresh list; relogin if necessary.', tags:['online']},
  {id:'GME_40', cat:'Gaming', q:'Console shows black screen after update', a:'Boot to safe mode, rebuild database or factory reset after backup.', tags:['update','boot']},

  /* MICROWAVE (40) */
  {id:'MIC_01', cat:'Microwave', q:'Microwave not heating', a:'Check door switch, magnetron, and power fuse.', tags:['heat']},
  {id:'MIC_02', cat:'Microwave', q:'Sparking inside cavity', a:'Remove metal, check waveguide cover.', tags:['spark']},
  {id:'MIC_03', cat:'Microwave', q:'Turntable not rotating', a:'Check motor, drive bushing, ensure tray seated.', tags:['turntable']},
  {id:'MIC_04', cat:'Microwave', q:'Buttons not responding', a:'Clean control panel, check membrane or PCB.', tags:['panel']},
  {id:'MIC_05', cat:'Microwave', q:'Door won’t close properly', a:'Inspect latch hooks, hinges, replace broken latch.', tags:['door']},
  {id:'MIC_06', cat:'Microwave', q:'Light not working', a:'Replace bulb, check socket and door switch.', tags:['light']},
  {id:'MIC_07', cat:'Microwave', q:'Unusual noise', a:'Inspect turntable motor, fan, magnetron.', tags:['noise']},
  {id:'MIC_08', cat:'Microwave', q:'Stops mid-cycle', a:'Check power supply, faulty door switch, thermal fuse.', tags:['power']},
  {id:'MIC_09', cat:'Microwave', q:'Clock not keeping time', a:'Reset power, replace control board if recurring.', tags:['clock']},
  {id:'MIC_10', cat:'Microwave', q:'Smoke from vent', a:'Unplug immediately, clean food residue, inspect magnetron.', tags:['smoke']},
  {id:'MIC_11', cat:'Microwave', q:'Plate wobbling', a:'Ensure correct roller ring, clean base.', tags:['turntable']},
  {id:'MIC_12', cat:'Microwave', q:'Display dim or blank', a:'Check display board or control PCB.', tags:['display']},
  {id:'MIC_13', cat:'Microwave', q:'Starts by itself', a:'Unplug, check stuck keypad or control relay.', tags:['safety']},
  {id:'MIC_14', cat:'Microwave', q:'No power', a:'Check outlet, fuse, thermal cutout.', tags:['power']},
  {id:'MIC_15', cat:'Microwave', q:'Cooking uneven', a:'Clean interior, rotate food, check turntable motor.', tags:['cooking']},
  {id:'MIC_16', cat:'Microwave', q:'Burnt smell', a:'Clean interior, inspect waveguide, avoid metallic objects.', tags:['smell']},
  {id:'MIC_17', cat:'Microwave', q:'Keypad beeps constantly', a:'Unplug, clean keypad, replace control PCB.', tags:['keypad']},
  {id:'MIC_18', cat:'Microwave', q:'Fuse blows repeatedly', a:'Check door switch and magnetron.', tags:['fuse']},
  {id:'MIC_19', cat:'Microwave', q:'Runs with door open', a:'Unplug immediately, door switch failure (unsafe).', tags:['door']},
  {id:'MIC_20', cat:'Microwave', q:'Turntable light flickers', a:'Tighten bulb socket, check wiring.', tags:['light']},

  {id:'MIC_21', cat:'Microwave', q:'Grill element not working', a:'Check grill filament and connections; replace if faulty.', tags:['grill']},
  {id:'MIC_22', cat:'Microwave', q:'Control panel faded', a:'Avoid harsh cleaners, replace membrane if worn.', tags:['panel']},
  {id:'MIC_23', cat:'Microwave', q:'Microwave door seal worn', a:'Replace door seal/gasket to maintain proper shielding.', tags:['door','seal']},
  {id:'MIC_24', cat:'Microwave', q:'Touchscreen unresponsive', a:'Power cycle, check for moisture, replace control board if needed.', tags:['panel']},
  {id:'MIC_25', cat:'Microwave', q:'Microwave trips breaker', a:'Check mains wiring, magnetron short, and high current draw.', tags:['power','breaker']},
  {id:'MIC_26', cat:'Microwave', q:'Glass tray cracking', a:'Ensure correct tray placement, replace roller ring, avoid heavy loads.', tags:['turntable']},
  {id:'MIC_27', cat:'Microwave', q:'Weird taste in food after cooking', a:'Clean cavity, check for burnt residues or metallic contamination.', tags:['smell','clean']},
  {id:'MIC_28', cat:'Microwave', q:'Microwave has strong humming', a:'Could be magnetron or transformer — seek technician.', tags:['noise']},
  {id:'MIC_29', cat:'Microwave', q:'Auto-cook not starting', a:'Check sensor and door switch, ensure correct food placement.', tags:['cooking','sensor']},
  {id:'MIC_30', cat:'Microwave', q:'Sensor cooking inaccurate', a:'Clean humidity/smell sensor and recalibrate if supported.', tags:['sensor']},
  {id:'MIC_31', cat:'Microwave', q:'Turntable motor hums but won’t spin', a:'Replace motor or drive bushing; check for obstructions.', tags:['turntable']},
  {id:'MIC_32', cat:'Microwave', q:'Exterior getting hot', a:'Check ventilation, ensure proper installation and clearance.', tags:['safety']},
  {id:'MIC_33', cat:'Microwave', q:'Microwave stops when door opened', a:'This is normal safety behavior; if it doesn’t stop, unplug and service.', tags:['safety']},
  {id:'MIC_34', cat:'Microwave', q:'Control panel language changed', a:'Reset language setting or perform factory reset.', tags:['settings']},
  {id:'MIC_35', cat:'Microwave', q:'Microwave beeps but won’t heat', a:'Possible magnetron or high-voltage fault — inspect internals safely.', tags:['heat','fault']},
  {id:'MIC_36', cat:'Microwave', q:'Door latch broken', a:'Replace latch assembly to ensure proper safety and operation.', tags:['door']},
  {id:'MIC_37', cat:'Microwave', q:'Microwave odor even after cleaning', a:'Check fan/vent for grease and clean thoroughly.', tags:['clean','vent']},
  {id:'MIC_38', cat:'Microwave', q:'Turntable glass stuck', a:'Lift and re-seat tray, clean roller ring and track.', tags:['turntable']},
  {id:'MIC_39', cat:'Microwave', q:'Microwave emits buzzing only', a:'Likely high-voltage transformer/magnetron failure — service required.', tags:['noise','fault']},
  {id:'MIC_40', cat:'Microwave', q:'Microwave control buttons worn off', a:'Replace membrane or control panel to restore markings.', tags:['panel','repair']}
];
