// kb.js — 20 Q&A per category (iPhone, Tablet, Google, Phone, Drone, Desktop, Laptop, Watch, Gaming, Microwave)

const KB = [
  /* iPHONE (20) — prefix IPH_ */
  {id:'IPH_01', cat:'iPhone', q:'iPhone not charging', a:'Try different cable/charger, clean Lightning port, force restart; replace port or battery if hardware.', tags:['charging']},
  {id:'IPH_02', cat:'iPhone', q:'Battery drains fast', a:'Check battery health in settings, reduce background app refresh and brightness; replace battery if <80%.', tags:['battery']},
  {id:'IPH_03', cat:'iPhone', q:'iPhone overheats', a:'Close heavy apps, remove case, avoid charging in sun; update iOS and apps.', tags:['overheat']},
  {id:'IPH_04', cat:'iPhone', q:'Face ID not working', a:'Ensure nothing blocks TrueDepth camera, update iOS, reset Face ID and re-enroll face.', tags:['faceid','camera']},
  {id:'IPH_05', cat:'iPhone', q:'iPhone frozen/black screen', a:'Force restart (volume up, volume down, hold side), connect to charger and try again.', tags:['boot']},
  {id:'IPH_06', cat:'iPhone', q:'Apps crashing', a:'Update apps/iOS, offload or reinstall offending app, free storage.', tags:['apps']},
  {id:'IPH_07', cat:'iPhone', q:'No sound from speaker', a:'Check volume & mute switch, disable Bluetooth, clean speaker grill, restart.', tags:['audio']},
  {id:'IPH_08', cat:'iPhone', q:'Wi-Fi disconnects', a:'Forget network, reboot router & phone, reset network settings.', tags:['wifi']},
  {id:'IPH_09', cat:'iPhone', q:'Slow performance', a:'Check storage and battery health; update iOS; disable background refresh.', tags:['speed']},
  {id:'IPH_10', cat:'iPhone', q:'Touchscreen unresponsive', a:'Remove screen protector, clean display, force restart; replace digitizer if hardware.', tags:['touch']},
  {id:'IPH_11', cat:'iPhone', q:'Camera blurry', a:'Clean lens, close and reopen Camera app, test other camera apps, repair if physical.', tags:['camera']},
  {id:'IPH_12', cat:'iPhone', q:'Unable to update iOS', a:'Free up storage, plug into power & Wi-Fi, try updating via Finder/iTunes.', tags:['update']},
  {id:'IPH_13', cat:'iPhone', q:'SIM not detected', a:'Reseat SIM, test SIM in another phone, reset network settings.', tags:['sim','network']},
  {id:'IPH_14', cat:'iPhone', q:'Bluetooth pairing fails', a:'Toggle Bluetooth, remove old pairings, restart both devices.', tags:['bluetooth']},
  {id:'IPH_15', cat:'iPhone', q:'iMessage not sending', a:'Check network, sign out/in of Apple ID, enable iMessage under settings.', tags:['imessage']},
  {id:'IPH_16', cat:'iPhone', q:'FaceTime poor quality', a:'Use Wi-Fi, close other apps, update iOS, test on another connection.', tags:['facetime']},
  {id:'IPH_17', cat:'iPhone', q:'Green tint on display', a:'Update iOS, reboot; if persists possible hardware issue (screen), visit repair.', tags:['display']},
  {id:'IPH_18', cat:'iPhone', q:'Charging slow', a:'Try higher watt charger, clean port, test wireless charging pad.', tags:['charging']},
  {id:'IPH_19', cat:'iPhone', q:'Apps notifications not appearing', a:'Check app notification settings and Focus/Do Not Disturb.', tags:['notifications']},
  {id:'IPH_20', cat:'iPhone', q:'Water exposure — what to do', a:'Power off immediately, dry and leave open in airflow; do not charge until dry; seek repair if symptoms persist.', tags:['water']},

  /* TABLET (20) */
  {id:'TAB_01', cat:'Tablet', q:'Tablet won’t charge', a:'Check charger/port, try different cable, clean port and restart.', tags:['charging']},
  {id:'TAB_02', cat:'Tablet', q:'Tablet slow or laggy', a:'Close apps, clear storage, update OS, consider factory reset.', tags:['speed']},
  {id:'TAB_03', cat:'Tablet', q:'Screen cracked', a:'Avoid using with shards, back up data, replace screen assembly.', tags:['screen']},
  {id:'TAB_04', cat:'Tablet', q:'Wi-Fi keeps dropping', a:'Restart router/tablet, forget network, update firmware.', tags:['wifi']},
  {id:'TAB_05', cat:'Tablet', q:'Touchscreen ghost touches', a:'Remove protector, reboot, recalibrate if available, replace digitizer if persistent.', tags:['touch']},
  {id:'TAB_06', cat:'Tablet', q:'Apps won’t install', a:'Check storage and account settings, clear app store cache, retry.', tags:['apps']},
  {id:'TAB_07', cat:'Tablet', q:'Battery swollen', a:'Stop using, do not puncture, seek professional battery replacement.', tags:['battery']},
  {id:'TAB_08', cat:'Tablet', q:'Tablet won’t turn on', a:'Charge for 30 min, try different charger, force restart sequence.', tags:['power']},
  {id:'TAB_09', cat:'Tablet', q:'Audio not working', a:'Check volume, Bluetooth routing, test headphones and speaker.', tags:['audio']},
  {id:'TAB_10', cat:'Tablet', q:'Overheating during use', a:'Avoid heavy apps for long periods, remove case, update apps.', tags:['overheat']},
  {id:'TAB_11', cat:'Tablet', q:'Camera failing', a:'Restart app, clear camera cache, test with other apps, update OS.', tags:['camera']},
  {id:'TAB_12', cat:'Tablet', q:'Stylus not working', a:'Replace tip, pair again, charge stylus, check app settings.', tags:['stylus']},
  {id:'TAB_13', cat:'Tablet', q:'Screen dim/brightness issue', a:'Disable auto-brightness, update drivers/firmware, test brightness slider.', tags:['display']},
  {id:'TAB_14', cat:'Tablet', q:'Tablet freezes while gaming', a:'Lower graphics settings, close background apps, ensure temperature kept low.', tags:['gaming']},
  {id:'TAB_15', cat:'Tablet', q:'Bluetooth keyboard not pairing', a:'Put keyboard in pairing mode, remove old pairings, restart tablet.', tags:['bluetooth']},
  {id:'TAB_16', cat:'Tablet', q:'Storage full quickly', a:'Clear cache, uninstall unused apps, move media to cloud or SD card if possible.', tags:['storage']},
  {id:'TAB_17', cat:'Tablet', q:'Touch ID not recognized', a:'Re-enroll fingerprints, clean sensor and fingers.', tags:['security']},
  {id:'TAB_18', cat:'Tablet', q:'GPS inaccurate', a:'Enable high accuracy mode, calibrate compass, update maps.', tags:['gps']},
  {id:'TAB_19', cat:'Tablet', q:'Screen flicker', a:'Update OS, test safe mode, check for loose connectors (repair).', tags:['display']},
  {id:'TAB_20', cat:'Tablet', q:'Factory reset tips', a:'Back up data, sign out of accounts, ensure charged battery before resetting.', tags:['reset']},

  /* GOOGLE (20) */
  {id:'GGL_01', cat:'Google', q:'Android not updating', a:'Free storage, stable Wi-Fi, plug in charger, try manual OTA via vendor tool.', tags:['update']},
  {id:'GGL_02', cat:'Google', q:'Google Play errors', a:'Clear Play Store cache/data, sign out/in of Google account, update Play Services.', tags:['playstore']},
  {id:'GGL_03', cat:'Google', q:'Google Assistant not working', a:'Check mic permission, language, and Assistant settings; update Google app.', tags:['assistant']},
  {id:'GGL_04', cat:'Google', q:'Pixel camera crash', a:'Clear camera app cache, update firmware, use safe mode to test.', tags:['camera']},
  {id:'GGL_05', cat:'Google', q:'Battery optimization kills apps', a:'Disable aggressive battery optimizations for trusted apps.', tags:['battery']},
  {id:'GGL_06', cat:'Google', q:'Random reboots on Android', a:'Check for faulty apps, wipe cache partition, factory reset after backup.', tags:['reboot']},
  {id:'GGL_07', cat:'Google', q:'Slow Android after update', a:'Reboot multiple times, clear cache, wait until background optimizations finish.', tags:['performance']},
  {id:'GGL_08', cat:'Google', q:'Notification channel missing', a:'Open app notifications and enable desired channels per app.', tags:['notifications']},
  {id:'GGL_09', cat:'Google', q:'Android won’t recognize SD card', a:'Unmount/remount, reformat (backup first), test card on PC.', tags:['sdcard']},
  {id:'GGL_10', cat:'Google', q:'Fingerprint sensor not working', a:'Re-register prints, ensure finger/sensor clean, remove screen protector near sensor.', tags:['security']},
  {id:'GGL_11', cat:'Google', q:'Mobile data slow', a:'Toggle airplane mode, reset APN, check carrier issues, test SIM in another phone.', tags:['network']},
  {id:'GGL_12', cat:'Google', q:'Bluetooth audio out of sync', a:'Toggle aptX/AAC options (if available), reconnect, update firmware.', tags:['bluetooth']},
  {id:'GGL_13', cat:'Google', q:'Device not charging rapidly', a:'Use original charger, enable fast-charge option in settings, try different cable.', tags:['charging']},
  {id:'GGL_14', cat:'Google', q:'Screen burn-in on OLED', a:'Reduce brightness, use dark themes, use pixel refresher apps where available.', tags:['display']},
  {id:'GGL_15', cat:'Google', q:'USB accessory not detected', a:'Enable OTG in settings, try different adapter/cable, check accessory compatibility.', tags:['usb']},
  {id:'GGL_16', cat:'Google', q:'Keyboard typing lag', a:'Change keyboard app, clear keyboard app cache, update firmware.', tags:['keyboard']},
  {id:'GGL_17', cat:'Google', q:'Apps failing to update', a:'Check Play Store, remove and re-add Google account, clear Store cache.', tags:['playstore']},
  {id:'GGL_18', cat:'Google', q:'Screen timeout too short', a:'Adjust display sleep settings or adaptive display options.', tags:['display']},
  {id:'GGL_19', cat:'Google', q:'Cast not found on TV', a:'Ensure both devices on same network and same Wi-Fi band, reboot router and devices.', tags:['cast']},
  {id:'GGL_20', cat:'Google', q:'Factory image restore tips', a:'Back up data, download verified image/tool from vendor, follow instructions carefully.', tags:['recovery']},

  /* PHONE (20) */
  {id:'PHN_01', cat:'Phone', q:'Phone won’t boot', a:'Try force restart, charge 15–30 minutes, boot to recovery and use repair tools.', tags:['boot']},
  {id:'PHN_02', cat:'Phone', q:'Cracked screen advice', a:'Back up immediately, avoid using cracked glass, replace screen assembly.', tags:['screen']},
  {id:'PHN_03', cat:'Phone', q:'Liquid damage steps', a:'Power off, remove SIM, dry with airflow and desiccants; avoid charging until dry.', tags:['water']},
  {id:'PHN_04', cat:'Phone', q:'Microphone not heard', a:'Check app permissions, test voice recorder, clean mic holes.', tags:['microphone']},
  {id:'PHN_05', cat:'Phone', q:'Phone hot during charge', a:'Use correct charger, remove case, avoid heavy use while charging.', tags:['overheat']},
  {id:'PHN_06', cat:'Phone', q:'Apps use too much data', a:'Restrict background data per app, use Wi-Fi for updates.', tags:['data']},
  {id:'PHN_07', cat:'Phone', q:'Unable to factory reset', a:'Use recovery mode or vendor PC tool; ensure credentials for FRP locks.', tags:['reset']},
  {id:'PHN_08', cat:'Phone', q:'SIM locked / PIN issues', a:'Enter correct PIN, use PUK code provided by carrier to unlock.', tags:['sim']},
  {id:'PHN_09', cat:'Phone', q:'Screen tint or color wrong', a:'Disable color filters, recalibrate display if available, update firmware.', tags:['display']},
  {id:'PHN_10', cat:'Phone', q:'Slow camera or app load', a:'Clear cache, free storage, close background processes.', tags:['camera']},
  {id:'PHN_11', cat:'Phone', q:'Phone vibrates but no ring', a:'Check Do Not Disturb and sound profile, test ringtone settings.', tags:['sound']},
  {id:'PHN_12', cat:'Phone', q:'Cellular data not working', a:'Reset APN settings, toggle airplane mode, reseat SIM, contact carrier.', tags:['network']},
  {id:'PHN_13', cat:'Phone', q:'Phone shows unknown charges', a:'Check app purchases, carrier bills, secure device and change passwords.', tags:['billing']},
  {id:'PHN_14', cat:'Phone', q:'Screen protector causing issues', a:'Remove protector and test; buy high-quality tempered glass.', tags:['accessory']},
  {id:'PHN_15', cat:'Phone', q:'Phone camera app shutter lag', a:'Clear camera cache, update app, test third-party camera.', tags:['camera']},
  {id:'PHN_16', cat:'Phone', q:'Unable to make calls', a:'Check signal, airplane mode, correct network mode and SIM placement.', tags:['calls']},
  {id:'PHN_17', cat:'Phone', q:'Slow app updates', a:'Restart device, clear Play/App Store cache, verify Wi-Fi speed.', tags:['update']},
  {id:'PHN_18', cat:'Phone', q:'Screen protector bubble removal', a:'Lift edge and reapply or replace with better alignment and dust-free environment.', tags:['screen']},
  {id:'PHN_19', cat:'Phone', q:'Phone camera not focusing', a:'Tap to focus, restart camera, update software; replace module if failing.', tags:['camera']},
  {id:'PHN_20', cat:'Phone', q:'Phone storage reporting wrong size', a:'Clear caches, remove large files, reboot; sometimes media scanning delays show wrong used space.', tags:['storage']},

 /* DRONE (20) */
  {id:'DRN_01', cat:'Drone', q:'Drone won’t take off', a:'Check battery charge, ensure props installed correctly and not damaged, verify motors spin in motor test, and confirm firmware is up to date.', tags:['flight']},
  {id:'DRN_02', cat:'Drone', q:'Drone GPS not locking', a:'Move to an open area with a clear sky, restart the drone and controller, wait for a full GPS lock before takeoff, and recalibrate the compass if needed.', tags:['gps']},
  {id:'DRN_03', cat:'Drone', q:'Drone drifting in hover', a:'Calibrate the IMU and compass, ensure the home point is set correctly, check for bent props or motor issues, and perform a test hover at low altitude.', tags:['drift','calibration']},
  {id:'DRN_04', cat:'Drone', q:'Propeller damaged', a:'Replace cracked or chipped propellers with manufacturer-approved spares and ensure each prop is installed in the correct orientation.', tags:['propeller']},
  {id:'DRN_05', cat:'Drone', q:'Controller not binding', a:'Follow the manufacturer binding procedure, ensure both devices are charged, and confirm firmware versions are compatible before retrying the bind.', tags:['pairing']},
  {id:'DRN_06', cat:'Drone', q:'Drone loses video feed', a:'Reduce distance, check antenna alignment on both drone and controller, update transmitter/receiver firmware, and test with another device to isolate the issue.', tags:['video','transmission']},
  {id:'DRN_07', cat:'Drone', q:'Battery swelling', a:'Stop using a swollen battery immediately, dispose of it safely per local regulations, and replace with a healthy battery from a trusted source.', tags:['battery','safety']},
  {id:'DRN_08', cat:'Drone', q:'Motors making unusual noise', a:'Inspect motors for debris, check motor bearings, ensure props are tight and not rubbing the frame; replace motors if bearings are failing.', tags:['motor']},
  {id:'DRN_09', cat:'Drone', q:'Failsafe return-to-home triggers unexpectedly', a:'Check GPS and compass status before flight, set a safe RTH altitude, verify GPS lock, and ensure no geofencing or firmware restrictions are active.', tags:['rth','gps']},
  {id:'DRN_10', cat:'Drone', q:'Firmware update failed', a:'Ensure batteries are fully charged, use a stable internet connection, follow vendor recovery steps if update fails, and retry the process.', tags:['firmware']},
  {id:'DRN_11', cat:'Drone', q:'Gimbal not stabilizing', a:'Check gimbal mounting screws, balance the camera payload, recalibrate gimbal in the app, and update gimbal firmware if available.', tags:['gimbal']},
  {id:'DRN_12', cat:'Drone', q:'Remote control range reduced', a:'Verify antenna orientation, avoid areas with RF interference, update firmware, and test with different locations to isolate interference sources.', tags:['range','antenna']},
  {id:'DRN_13', cat:'Drone', q:'SD card not recording', a:'Use recommended speed-class cards, format the card in the drone, ensure it’s seated correctly, and try a different card to rule out media failure.', tags:['storage','sd']},
  {id:'DRN_14', cat:'Drone', q:'Calibration errors persist', a:'Place the drone on a flat, level surface, remove propellers if instructed, follow the exact manufacturer steps for IMU and compass calibration, and avoid nearby metal objects.', tags:['calibration']},
  {id:'DRN_15', cat:'Drone', q:'Drone won’t arm', a:'Check preflight conditions (GPS lock, battery level, prop guards removed), ensure geofence or flight restrictions aren’t blocking arming, and consult the app status messages for specific errors.', tags:['arming']},
  {id:'DRN_16', cat:'Drone', q:'Telemetry disconnects intermittently', a:'Inspect antenna connections, reduce obstructions between controller and drone, avoid high-interference areas, and update radio firmware.', tags:['telemetry']},
  {id:'DRN_17', cat:'Drone', q:'Drone flips or tumbles at takeoff', a:'Immediately land if safe, inspect prop orientation and tightness, check motor direction and ESC wiring, and verify flight controller mounting and PID settings.', tags:['flight','safety']},
  {id:'DRN_18', cat:'Drone', q:'ESC / motor error shown in app', a:'Power off and replug battery, check motor and ESC connections, update ESC firmware, and replace any ESC or motor that shows hardware faults.', tags:['esc','motor']},
  {id:'DRN_19', cat:'Drone', q:'Camera tilt or gimbal stuck', a:'Power-cycle the drone, recalibrate the gimbal through the app, check for physical obstructions, and inspect gimbal cables for damage.', tags:['gimbal','camera']},
  {id:'DRN_20', cat:'Drone', q:'No live view on mobile app', a:'Confirm the camera stream settings, reconnect phone to controller Wi-Fi or proxy, ensure app permissions are granted, and update both app and drone firmware.', tags:['video','app']},

  /* DESKTOP (20) */
  {id:'DSK_01', cat:'Desktop', q:'Desktop won’t power on', a:'Check power cable, PSU switch, reseat RAM and cables.', tags:['power']},
  {id:'DSK_02', cat:'Desktop', q:'No display signal', a:'Check monitor cable, GPU seated, try onboard graphics.', tags:['display']},
  {id:'DSK_03', cat:'Desktop', q:'Boot device not found', a:'Check BIOS boot order, reseat or replace SSD/HDD.', tags:['boot']},
  {id:'DSK_04', cat:'Desktop', q:'Fan noisy', a:'Clean dust, replace worn bearings, ensure fans not hitting cables.', tags:['fan']},
  {id:'DSK_05', cat:'Desktop', q:'Overheating CPU', a:'Reapply thermal paste, clean heatsink, check fan curve.', tags:['temperature']},
  {id:'DSK_06', cat:'Desktop', q:'USB ports not working', a:'Check BIOS settings, reinstall chipset drivers.', tags:['usb']},
  {id:'DSK_07', cat:'Desktop', q:'System freezes randomly', a:'Check RAM stability, PSU quality, update BIOS.', tags:['freeze']},
  {id:'DSK_08', cat:'Desktop', q:'Blue screen errors', a:'Note error code, update drivers, run memory diagnostic.', tags:['bsod']},
  {id:'DSK_09', cat:'Desktop', q:'No internet connection', a:'Check Ethernet cable, driver status, IP config.', tags:['network']},
  {id:'DSK_10', cat:'Desktop', q:'Slow startup', a:'Disable startup apps, switch HDD to SSD.', tags:['performance']},
  {id:'DSK_11', cat:'Desktop', q:'Keyboard not detected', a:'Plug into another port, replace keyboard, reset BIOS.', tags:['keyboard']},
  {id:'DSK_12', cat:'Desktop', q:'GPU overheating', a:'Clean fans, adjust airflow, repaste GPU.', tags:['gpu']},
  {id:'DSK_13', cat:'Desktop', q:'Audio crackling', a:'Update sound driver, test other audio outputs.', tags:['audio']},
  {id:'DSK_14', cat:'Desktop', q:'CMOS reset needed', a:'Remove battery 5 min, reinsert, reset time/date.', tags:['bios']},
  {id:'DSK_15', cat:'Desktop', q:'No POST beep', a:'Check speaker connection, verify RAM/GPU seated.', tags:['post']},
  {id:'DSK_16', cat:'Desktop', q:'LAN port light off', a:'Test other cable, enable LAN in BIOS.', tags:['network']},
  {id:'DSK_17', cat:'Desktop', q:'PC restarts itself', a:'Check PSU wattage, update BIOS, check overheating.', tags:['power']},
  {id:'DSK_18', cat:'Desktop', q:'SSD not detected', a:'Reconnect SATA cable, update BIOS firmware.', tags:['storage']},
  {id:'DSK_19', cat:'Desktop', q:'Mouse lag', a:'Use USB 2.0 port, clean sensor, check surface.', tags:['mouse']},
  {id:'DSK_20', cat:'Desktop', q:'Windows activation lost', a:'Sign into Microsoft account, run activation troubleshooter.', tags:['windows']},

  /* LAPTOP (20) */
  {id:'LAP_01', cat:'Laptop', q:'Laptop not charging', a:'Check charger/port, battery health, update BIOS.', tags:['charging']},
  {id:'LAP_02', cat:'Laptop', q:'Battery drains fast', a:'Lower brightness, close apps, use battery saver.', tags:['battery']},
  {id:'LAP_03', cat:'Laptop', q:'Overheating', a:'Clean fans, use cooling pad, repaste CPU/GPU.', tags:['temperature']},
  {id:'LAP_04', cat:'Laptop', q:'Keyboard not typing', a:'Check for stuck keys, reinstall drivers, external test.', tags:['keyboard']},
  {id:'LAP_05', cat:'Laptop', q:'Touchpad not working', a:'Enable in settings, update driver, check Fn key toggle.', tags:['touchpad']},
  {id:'LAP_06', cat:'Laptop', q:'Display flickering', a:'Update GPU driver, change refresh rate, test safe mode.', tags:['display']},
  {id:'LAP_07', cat:'Laptop', q:'Wi-Fi dropping', a:'Reinstall driver, reset network stack, toggle airplane mode.', tags:['wifi']},
  {id:'LAP_08', cat:'Laptop', q:'Audio not working', a:'Select correct output, reinstall driver, test headphones.', tags:['audio']},
  {id:'LAP_09', cat:'Laptop', q:'USB port dead', a:'Check power management USB suspend settings.', tags:['usb']},
  {id:'LAP_10', cat:'Laptop', q:'Webcam not detected', a:'Enable in BIOS, reinstall camera driver.', tags:['camera']},
  {id:'LAP_11', cat:'Laptop', q:'No boot device', a:'Check boot order, reinstall OS, test drive.', tags:['boot']},
  {id:'LAP_12', cat:'Laptop', q:'Fan noise', a:'Clean vents, adjust fan curve, replace faulty fan.', tags:['fan']},
  {id:'LAP_13', cat:'Laptop', q:'Trackpad gesture fail', a:'Update precision driver, re-enable gestures.', tags:['touchpad']},
  {id:'LAP_14', cat:'Laptop', q:'Battery not detected', a:'Disconnect AC, hold power 30s, reconnect battery.', tags:['battery']},
  {id:'LAP_15', cat:'Laptop', q:'HDMI not working', a:'Reconnect cable, change display mode (Win+P).', tags:['display']},
  {id:'LAP_16', cat:'Laptop', q:'Slow performance', a:'Disable startup apps, upgrade to SSD, add RAM.', tags:['performance']},
  {id:'LAP_17', cat:'Laptop', q:'Touchscreen not responding', a:'Recalibrate, update HID driver.', tags:['touch']},
  {id:'LAP_18', cat:'Laptop', q:'Blue screen errors', a:'Update drivers, check RAM, run system file check.', tags:['bsod']},
  {id:'LAP_19', cat:'Laptop', q:'Sleep mode issues', a:'Change power plan, update BIOS, disable hybrid sleep.', tags:['sleep']},
  {id:'LAP_20', cat:'Laptop', q:'Overcharge protection', a:'Enable battery care mode if available.', tags:['battery']},

  /* WATCH (20) */
  {id:'WCH_01', cat:'Watch', q:'Watch not turning on', a:'Charge for at least 30 minutes, try reset sequence.', tags:['power']},
  {id:'WCH_02', cat:'Watch', q:'Watch not syncing', a:'Toggle Bluetooth, reopen app, restart both devices.', tags:['sync']},
  {id:'WCH_03', cat:'Watch', q:'Step count inaccurate', a:'Tighten strap, calibrate motion sensors.', tags:['sensor']},
  {id:'WCH_04', cat:'Watch', q:'Battery draining fast', a:'Reduce brightness, disable always-on display.', tags:['battery']},
  {id:'WCH_05', cat:'Watch', q:'Heart rate sensor not reading', a:'Clean underside, tighten band, restart device.', tags:['sensor']},
  {id:'WCH_06', cat:'Watch', q:'App notifications missing', a:'Enable app access in wearable app settings.', tags:['notifications']},
  {id:'WCH_07', cat:'Watch', q:'Watch overheats', a:'Remove from wrist, close apps, update firmware.', tags:['heat']},
  {id:'WCH_08', cat:'Watch', q:'Touchscreen lag', a:'Reboot, reduce animations, clear cache.', tags:['touch']},
  {id:'WCH_09', cat:'Watch', q:'Display dim outdoors', a:'Enable auto-brightness or raise brightness manually.', tags:['display']},
  {id:'WCH_10', cat:'Watch', q:'Charging cradle not connecting', a:'Clean contacts, use OEM charger.', tags:['charging']},
  {id:'WCH_11', cat:'Watch', q:'Time not accurate', a:'Sync with phone or internet time server.', tags:['time']},
  {id:'WCH_12', cat:'Watch', q:'Firmware update failed', a:'Retry with enough battery and Wi-Fi.', tags:['firmware']},
  {id:'WCH_13', cat:'Watch', q:'Strap sensor error', a:'Clean contacts, reconnect strap.', tags:['sensor']},
  {id:'WCH_14', cat:'Watch', q:'Screen cracked', a:'Replace screen via authorized service.', tags:['screen']},
  {id:'WCH_15', cat:'Watch', q:'No vibration alerts', a:'Check vibration intensity settings.', tags:['vibration']},
  {id:'WCH_16', cat:'Watch', q:'Watch not pairing', a:'Reset Bluetooth pair list and retry.', tags:['bluetooth']},
  {id:'WCH_17', cat:'Watch', q:'GPS off-track', a:'Enable high accuracy, update AGPS data.', tags:['gps']},
  {id:'WCH_18', cat:'Watch', q:'Charging slow', a:'Try different adapter, clean contacts.', tags:['charging']},
  {id:'WCH_19', cat:'Watch', q:'Voice assistant not responding', a:'Reconnect to phone, check microphone permissions.', tags:['assistant']},
  {id:'WCH_20', cat:'Watch', q:'Water detected alert stuck', a:'Dry watch, restart, toggle water ejection mode.', tags:['water']},

  /* GAMING (20) */
  {id:'GME_01', cat:'Gaming', q:'Console not powering', a:'Check power cable, surge protector, reset PSU.', tags:['power']},
  {id:'GME_02', cat:'Gaming', q:'Controller drift', a:'Clean analog stick, recalibrate, replace module.', tags:['controller']},
  {id:'GME_03', cat:'Gaming', q:'No video signal', a:'Check HDMI port and cable, set correct input.', tags:['display']},
  {id:'GME_04', cat:'Gaming', q:'Game freezes', a:'Restart system, clear cache, reinstall game.', tags:['crash']},
  {id:'GME_05', cat:'Gaming', q:'Slow downloads', a:'Pause/resume download, use wired connection.', tags:['network']},
  {id:'GME_06', cat:'Gaming', q:'Overheating console', a:'Clean vents, elevate console, ensure airflow.', tags:['heat']},
  {id:'GME_07', cat:'Gaming', q:'No sound in game', a:'Check output device, HDMI audio, and console sound settings.', tags:['audio']},
  {id:'GME_08', cat:'Gaming', q:'Disc not reading', a:'Clean disc, update firmware, test another disc.', tags:['disc']},
  {id:'GME_09', cat:'Gaming', q:'Cannot connect online', a:'Test internet connection, check NAT type.', tags:['online']},
  {id:'GME_10', cat:'Gaming', q:'Lag during online play', a:'Use wired Ethernet, close background downloads.', tags:['network']},
  {id:'GME_11', cat:'Gaming', q:'Save data lost', a:'Enable cloud sync, back up regularly.', tags:['save']},
  {id:'GME_12', cat:'Gaming', q:'Controller won’t connect', a:'Pair again, reset controller, update firmware.', tags:['controller']},
  {id:'GME_13', cat:'Gaming', q:'Console crashes on startup', a:'Boot in safe mode, rebuild database.', tags:['boot']},
  {id:'GME_14', cat:'Gaming', q:'Fan too loud', a:'Clean dust, ensure console not enclosed.', tags:['fan']},
  {id:'GME_15', cat:'Gaming', q:'Account login issue', a:'Reset password, verify email, check server status.', tags:['account']},
  {id:'GME_16', cat:'Gaming', q:'Storage full', a:'Delete unused games, move to external drive.', tags:['storage']},
  {id:'GME_17', cat:'Gaming', q:'Update fails', a:'Restart console, check internet, retry.', tags:['update']},
  {id:'GME_18', cat:'Gaming', q:'Game won’t install', a:'Clear cache, ensure storage free, reinstall.', tags:['install']},
  {id:'GME_19', cat:'Gaming', q:'Console not detecting controller', a:'Use USB pairing, replace cable.', tags:['controller']},
  {id:'GME_20', cat:'Gaming', q:'No internet after update', a:'Reset network settings, reboot router.', tags:['network']},

  /* MICROWAVE (20) */
  {id:'MIC_01', cat:'Microwave', q:'Microwave not heating', a:'Check door switch, magnetron, and power fuse.', tags:['heat']},
  {id:'MIC_02', cat:'Microwave', q:'Sparking inside cavity', a:'Remove metal, check waveguide cover.', tags:['spark']},
  {id:'MIC_03', cat:'Microwave', q:'Turntable not rotating', a:'Check motor, drive bushing, ensure tray seated.', tags:['turntable']},
  {id:'MIC_04', cat:'Microwave', q:'Buttons not responding', a:'Clean control panel, check membrane or PCB.', tags:['panel']},
  {id:'MIC_05', cat:'Microwave', q:'Door won’t close properly', a:'Inspect latch hooks, hinges, replace broken latch.', tags:['door']},
  {id:'MIC_06', cat:'Microwave', q:'Light not working', a:'Replace bulb, check socket and door switch.', tags:['light']},
  {id:'MIC_07', cat:'Microwave', q:'Unusual noise', a:'Inspect turntable motor, fan, magnetron.', tags:['noise']},
  {id:'MIC_08', cat:'Microwave', q:'Stops mid-cycle', a:'Check power supply, faulty door switch, thermal fuse.', tags:['power']},
  {id:'MIC_09', cat:'Microwave', q:'Clock not keeping time', a:'Reset power, replace control board if recurring.', tags:['clock']},
  {id:'MIC_10', cat:'Microwave', q:'Smoke from vent', a:'Unplug immediately, clean food residue, inspect magnetron.', tags:['smoke']},
  {id:'MIC_11', cat:'Microwave', q:'Plate wobbling', a:'Ensure correct roller ring, clean base.', tags:['turntable']},
  {id:'MIC_12', cat:'Microwave', q:'Display dim or blank', a:'Check display board or control PCB.', tags:['display']},
  {id:'MIC_13', cat:'Microwave', q:'Starts by itself', a:'Unplug, check stuck keypad or control relay.', tags:['safety']},
  {id:'MIC_14', cat:'Microwave', q:'No power', a:'Check outlet, fuse, thermal cutout.', tags:['power']},
  {id:'MIC_15', cat:'Microwave', q:'Cooking uneven', a:'Clean interior, rotate food, check turntable motor.', tags:['cooking']},
  {id:'MIC_16', cat:'Microwave', q:'Burnt smell', a:'Clean interior, inspect waveguide, avoid metallic objects.', tags:['smell']},
  {id:'MIC_17', cat:'Microwave', q:'Keypad beeps constantly', a:'Unplug, clean keypad, replace control PCB.', tags:['keypad']},
  {id:'MIC_18', cat:'Microwave', q:'Fuse blows repeatedly', a:'Check door switch and magnetron.', tags:['fuse']},
  {id:'MIC_19', cat:'Microwave', q:'Runs with door open', a:'Unplug immediately, door switch failure (unsafe).', tags:['door']},
  {id:'MIC_20', cat:'Microwave', q:'Turntable light flickers', a:'Tighten bulb socket, check wiring.', tags:['light']}
];
